packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  fsevents: true
  workerd: true

minimumReleaseAgeExclude:
  - "@opencode/*"
  - ai
  - "@ai-sdk/*"
  - "@voidzero-dev/vite-plus-*"
  - vite-plus
  - oxlint
  - oxlint-tsgolint
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - "@oxc-project/*"
  - "@vitest/*"
  - vitest
  - wrangler
  - miniflare
  - workerd
  - "@cloudflare/*"
  - unenv
  - react
  - react-dom
  - scheduler
  - "@types/react"
  - "@types/react-dom"
  - "@types/node"
  - happy-dom
  - zod

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.3.1"
